version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers

    steps:
      - checkout
      - run: 
          name: build dependencies
          command: bundle install
          
      - run:
          name: Build the jekyll site
          command: bundle exec jekyll build

