version: 2
jobs:
  say-hello:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
